INSERT INTO ingredients (name, status) VALUES
('Gạo', 'APPROVED'),
('Mỳ Ý', 'APPROVED'),
('Thịt heo', 'APPROVED'),
('Thịt bò', 'APPROVED'),
('Gà', 'APPROVED'),
('Tôm', 'APPROVED'),
('Cá hồi', 'APPROVED'),
('Cá thu', 'APPROVED'),
('Trứng gà', 'APPROVED'),
('Sữa tươi', 'APPROVED'),
('Bơ', 'APPROVED'),
('Dầu ăn', 'APPROVED'),
('Đường', 'APPROVED'),
('Muối', 'APPROVED'),
('Tiêu', 'APPROVED'),
('Hành tím', 'APPROVED'),
('Hành tây', 'APPROVED'),
('Tỏi', 'APPROVED'),
('Ớt', 'APPROVED'),
('Rau muống', 'APPROVED'),
('Cải thìa', 'APPROVED'),
('Bắp cải', 'APPROVED'),
('Cà rốt', 'APPROVED'),
('Khoai tây', 'APPROVED'),
('Nấm rơm', 'APPROVED'),
('Nấm hương', 'APPROVED'),
('Mắm', 'APPROVED'),
('Nước tương', 'APPROVED'),
('Giấm', 'APPROVED'),
('Bánh mì', 'APPROVED');