// data/ingredients-list.ts
export const ingredientsList = {
  meat: [
    { nameVi: "Thịt gà", nameEn: "chicken breast" },
    { nameVi: "Thịt bò", nameEn: "beef" },
    { nameVi: "Thịt heo", nameEn: "pork" },
    { nameVi: "Thịt cừu", nameEn: "lamb" },
    { nameVi: "Thịt vịt", nameEn: "duck" },
    { nameVi: "Thịt ngan", nameEn: "goose" },
    { nameVi: "Thịt dê", nameEn: "goat" },
    { nameVi: "Tôm", nameEn: "shrimp" },
    { nameVi: "Tôm Hùm", nameEn: "King Crack" },
    { nameVi: "Cua", nameEn: "crab" },
    { nameVi: "Mực", nameEn: "squid" },
    { nameVi: "Cá hồi", nameEn: "salmon" },
    { nameVi: "Cá ngừ", nameEn: "tuna" },
    { nameVi: "Cá thu", nameEn: "mackerel" },
    { nameVi: "Cá basa", nameEn: "basa fish" },
    { nameVi: "Trứng gà", nameEn: "chicken egg" },
    { nameVi: "Trứng vịt", nameEn: "duck egg" },
    { nameVi: "Gan gà", nameEn: "chicken liver" },
    { nameVi: "Thịt heo xay", nameEn: "ground pork" },
    { nameVi: "Thịt bò xay", nameEn: "ground beef" },
    { nameVi: "Thịt gà xay", nameEn: "ground chicken" }
  ],

  vegetables: [
    { nameVi: "Cà rốt", nameEn: "carrot" },
    { nameVi: "Bắp cải", nameEn: "cabbage" },
    { nameVi: "Bông cải xanh", nameEn: "broccoli" },
    { nameVi: "Cải bó xôi", nameEn: "spinach" },
    { nameVi: "Củ hành", nameEn: "onion" },
    { nameVi: "Tỏi", nameEn: "garlic" },
    { nameVi: "Ớt chuông", nameEn: "bell pepper" },
    { nameVi: "Ớt hiểm", nameEn: "chili" },
    { nameVi: "Nấm rơm", nameEn: "straw mushroom" },
    { nameVi: "Nấm hương", nameEn: "shiitake mushroom" },
    { nameVi: "Nấm kim châm", nameEn: "enoki mushroom" },
    { nameVi: "Dưa leo", nameEn: "cucumber" },
    { nameVi: "Cà chua", nameEn: "tomato" },
    { nameVi: "Khoai tây", nameEn: "potato" },
    { nameVi: "Khoai lang", nameEn: "sweet potato" },
    { nameVi: "Ngô ngọt", nameEn: "corn" },
    { nameVi: "Đậu Hà Lan", nameEn: "green peas" },
    { nameVi: "Rau mùi", nameEn: "cilantro" },
    { nameVi: "Hành lá", nameEn: "green onion" },
    { nameVi: "Rau cải ngọt", nameEn: "bok choy" }
  ],

  spices: [
    { nameVi: "Muối", nameEn: "salt" },
    { nameVi: "Tiêu", nameEn: "black pepper" },
    { nameVi: "Đường", nameEn: "sugar" },
    { nameVi: "Nước tương", nameEn: "soy sauce" },
    { nameVi: "Nước mắm", nameEn: "fish sauce" },
    { nameVi: "Giấm", nameEn: "vinegar" },
    { nameVi: "Mật ong", nameEn: "honey" },
    { nameVi: "Ớt bột", nameEn: "chili powder" },
    { nameVi: "Bột ngọt", nameEn: "MSG" },
    { nameVi: "Hạt nêm", nameEn: "seasoning powder" },
    { nameVi: "Quế", nameEn: "cinnamon" },
    { nameVi: "Hồi", nameEn: "star anise" },
    { nameVi: "Đinh hương", nameEn: "clove" },
    { nameVi: "Tiêu trắng", nameEn: "white pepper" },
    { nameVi: "Gừng", nameEn: "ginger" },
    { nameVi: "Sả", nameEn: "lemongrass" },
    { nameVi: "Hành tím", nameEn: "shallot" },
    { nameVi: "Hạt thì là", nameEn: "cumin seeds" },
    { nameVi: "Bột ớt", nameEn: "paprika" },
    { nameVi: "Tỏi bột", nameEn: "garlic powder" }
  ],

  fruits: [
    { nameVi: "Táo", nameEn: "apple" },
    { nameVi: "Cam", nameEn: "orange" },
    { nameVi: "Chuối", nameEn: "banana" },
    { nameVi: "Dứa", nameEn: "pineapple" },
    { nameVi: "Dâu tây", nameEn: "strawberry" },
    { nameVi: "Việt quất", nameEn: "blueberry" },
    { nameVi: "Nho", nameEn: "grape" },
    { nameVi: "Mận", nameEn: "plum" },
    { nameVi: "Lê", nameEn: "pear" },
    { nameVi: "Xoài", nameEn: "mango" },
    { nameVi: "Đu đủ", nameEn: "papaya" },
    { nameVi: "Chôm chôm", nameEn: "rambutan" },
    { nameVi: "Thanh long", nameEn: "dragon fruit" },
    { nameVi: "Quýt", nameEn: "tangerine" },
    { nameVi: "Bưởi", nameEn: "pomelo" },
    { nameVi: "Ổi", nameEn: "guava" },
    { nameVi: "Mít", nameEn: "jackfruit" },
    { nameVi: "Dừa", nameEn: "coconut" },
    { nameVi: "Chanh", nameEn: "lemon" },
    { nameVi: "Bơ trái cây", nameEn: "avocado" }
  ],

  dairy: [
    { nameVi: "Sữa tươi", nameEn: "milk" },
    { nameVi: "Sữa đặc", nameEn: "condensed milk" },
    { nameVi: "Bơ", nameEn: "butter" },
    { nameVi: "Phô mai", nameEn: "cheese" },
    { nameVi: "Kem", nameEn: "ice cream" },
    { nameVi: "Sữa chua", nameEn: "yogurt" },
    { nameVi: "Kem tươi", nameEn: "whipped cream" },
    { nameVi: "Sữa hạnh nhân", nameEn: "almond milk" },
    { nameVi: "Sữa đậu nành", nameEn: "soy milk" },
    { nameVi: "Sữa dừa", nameEn: "coconut milk" },
    { nameVi: "Kem vani", nameEn: "vanilla ice cream" },
    { nameVi: "Phô mai tươi", nameEn: "cream cheese" },
    { nameVi: "Kem socola", nameEn: "chocolate ice cream" },
    { nameVi: "Bơ lạt", nameEn: "unsalted butter" },
    { nameVi: "Sữa bột", nameEn: "milk powder" },
    { nameVi: "Sữa đặc có đường", nameEn: "sweetened condensed milk" },
    { nameVi: "Sữa tách béo", nameEn: "skim milk" },
    { nameVi: "Kem trứng", nameEn: "egg custard" },
    { nameVi: "Sữa nguyên kem", nameEn: "whole milk" },
    { nameVi: "Phô mai Parmesan", nameEn: "parmesan cheese" }
  ],

  grains: [
    { nameVi: "Gạo", nameEn: "rice" },
    { nameVi: "Mì", nameEn: "noodles" },
    { nameVi: "Bánh mì", nameEn: "bread" },
    { nameVi: "Ngô ngọt", nameEn: "corn" },
    { nameVi: "Bánh bao", nameEn: "steamed bun" },
    { nameVi: "Bún", nameEn: "rice vermicelli" },
    { nameVi: "Hủ tiếu", nameEn: "rice noodle" },
    { nameVi: "Mỳ Ý", nameEn: "spaghetti" },
    { nameVi: "Yến mạch", nameEn: "oats" },
    { nameVi: "Ngũ cốc", nameEn: "cereal" },
    { nameVi: "Bánh ngọt", nameEn: "pastry" },
    { nameVi: "Bánh quy", nameEn: "cookies" },
    { nameVi: "Bánh pizza", nameEn: "pizza dough" },
    { nameVi: "Bánh xèo", nameEn: "savory pancake" },
    { nameVi: "Bánh đa", nameEn: "rice cracker" },
    { nameVi: "Bánh mì baguette", nameEn: "baguette" },
    { nameVi: "Bánh tẻ", nameEn: "steamed rice cake" },
    { nameVi: "Bánh khoai mì", nameEn: "cassava cake" },
    { nameVi: "Bánh bông lan", nameEn: "sponge cake" },
    { nameVi: "Bánh flan", nameEn: "caramel custard" }
  ],

  oils: [
    { nameVi: "Dầu ô liu", nameEn: "olive oil" },
    { nameVi: "Dầu ăn", nameEn: "vegetable oil" },
    { nameVi: "Dầu hướng dương", nameEn: "sunflower oil" },
    { nameVi: "Dầu mè", nameEn: "sesame oil" },
    { nameVi: "Dầu dừa", nameEn: "coconut oil" },
    { nameVi: "Dầu hạt cải", nameEn: "canola oil" },
    { nameVi: "Bơ lạt", nameEn: "unsalted butter" },
    { nameVi: "Bơ thực vật", nameEn: "margarine" },
    { nameVi: "Dầu nành", nameEn: "soybean oil" },
    { nameVi: "Dầu phộng", nameEn: "peanut oil" },
    { nameVi: "Dầu hạt nho", nameEn: "grape seed oil" },
    { nameVi: "Dầu bơ", nameEn: "avocado oil" },
    { nameVi: "Dầu hướng dương tinh luyện", nameEn: "refined sunflower oil" },
    { nameVi: "Dầu mè rang", nameEn: "roasted sesame oil" },
    { nameVi: "Dầu oliu nguyên chất", nameEn: "extra virgin olive oil" },
    { nameVi: "Dầu cọ", nameEn: "palm oil" },
    { nameVi: "Dầu hạt cải tinh luyện", nameEn: "refined canola oil" },
    { nameVi: "Dầu hạt lanh", nameEn: "flaxseed oil" },
    { nameVi: "Dầu hạt hướng dương ép lạnh", nameEn: "cold-pressed sunflower oil" },
    { nameVi: "Dầu óc chó", nameEn: "walnut oil" }
  ],
  unit : [
    { nameVi: "Thìa", nameEn: "spoon" },
    { nameVi: "g", nameEn: "g" },
  ]
};


export const unitMap: Record<string, number> = {
  thìa: 12.5,
  muỗng: 12.5,
  cup: 200,
  g: 1,
  ml: 1
};